[package]
name = "demiurge"
version = "0.0.1"
edition = "2024"
license = "MIT"

[lib]
name = "demiurge"
path = "src/lib/mod.rs"

[[bin]]
name = "demiurge"
path = "src/main.rs"

[dependencies]

[profile.dev]
opt-level = 0
debug = 0
incremental = true
codegen-units = 256

[profile.release]
opt-level = 3
debug = 0
lto = "fat"
codegen-units = 1
panic = "abort"
incremental = false
strip = "symbols"
